youtube:
  enabled: true
  config:
    max_cached_per_room: 5
    chunk_size: 8000

ai:
  enabled: true
  config:
    model: "deepseek/deepseek-chat-v3-0324:free" #"cognitivecomputations/dolphin3.0-mistral-24b:free"
    temperature: 0.3
    max_tokens: 500

media:
  enabled: true
  config:
    temp_dir: "./temp_media"
    max_file_size: "50MB"

database:
  enabled: true
  config:
    api_url: "https://base2.fungus.work"
    timeout: 30

core:
  enabled: true
  config:
    debug_enabled: true

example:
  enabled: true  # Disabled by default - this is a skeleton/template plugin
  config:
    demo_mode: true
    max_echo_length: 1000